// European countries in alphabetical order (French)
export const EUROPEAN_COUNTRIES = [
  'Albanie',
  'Allemagne',
  'Andorre',
  'Arménie',
  'Autriche',
  'Azerbaïdjan',
  'Belgique',
  'Biélorussie',
  'Bosnie-Herzégovine',
  'Bulgarie',
  'Chypre',
  'Croatie',
  'Danemark',
  'Espagne',
  'Estonie',
  'Finlande',
  'France',
  'Géorgie',
  'Grèce',
  'Hongrie',
  'Irlande',
  'Islande',
  'Italie',
  'Kazakhstan',
  'Kirghizistan',
  'Lettonie',
  'Liechtenstein',
  'Lituanie',
  'Luxembourg',
  'Macédoine du Nord',
  'Malte',
  'Moldavie',
  'Monaco',
  'Monténégro',
  'Norvège',
  'Ouzbékistan',
  'Pays-Bas',
  'Pologne',
  'Portugal',
  'République tchèque',
  'Roumanie',
  'Royaume-Uni',
  'Russie',
  'Saint-Marin',
  'Serbie',
  'Slovaquie',
  'Slovénie',
  'Suède',
  'Suisse',
  'Turquie',
  'Ukraine',
  'Vatican',
] as const;

export type EuropeanCountry = typeof EUROPEAN_COUNTRIES[number];
