// Nationality code to full name mapping
export const nationalityMap: Record<string, string> = {
  'SE': 'SWEDEN',
  'NO': 'NORWAY',
  'DK': 'DENMARK',
  'FI': 'FINLAND',
  'IS': 'ICELAND',
  'GB': 'UNITED KINGDOM',
  'FR': 'FRANCE',
  'DE': 'GERMANY',
  'ES': 'SPAIN',
  'IT': 'ITALY',
  'PT': 'PORTUGAL',
  'NL': 'NETHERLANDS',
  'BE': 'BELGIUM',
  'CH': 'SWITZERLAND',
  'AT': 'AUSTRIA',
  'PL': 'POLAND',
  'CZ': 'CZECHIA',
  'SK': 'SLOVAKIA',
  'HU': 'HUNGARY',
  'RO': 'ROMANIA',
  'BG': 'BULGARIA',
  'GR': 'GREECE',
  'TR': 'TURKEY',
  'RU': 'RUSSIA',
  'UA': 'UKRAINE',
  'EE': 'ESTONIA',
  'LV': 'LATVIA',
  'LT': 'LITHUANIA',
  'HR': 'CROATIA',
  'RS': 'SERBIA',
  'SI': 'SLOVENIA',
  'BA': 'BOSNIA',
  'MK': 'NORTH MACEDONIA',
  'AL': 'ALBANIA',
  'XK': 'KOSOVO',
  'US': 'UNITED STATES',
  'CA': 'CANADA',
  'MX': 'MEXICO',
  'BR': 'BRAZIL',
  'AR': 'ARGENTINA',
  'CL': 'CHILE',
  'CO': 'COLOMBIA',
  'PE': 'PERU',
  'VE': 'VENEZUELA',
  'CN': 'CHINA',
  'JP': 'JAPAN',
  'KR': 'SOUTH KOREA',
  'TW': 'TAIWAN',
  'HK': 'HONG KONG',
  'SG': 'SINGAPORE',
  'MY': 'MALAYSIA',
  'TH': 'THAILAND',
  'VN': 'VIETNAM',
  'PH': 'PHILIPPINES',
  'ID': 'INDONESIA',
  'IN': 'INDIA',
  'PK': 'PAKISTAN',
  'AU': 'AUSTRALIA',
  'NZ': 'NEW ZEALAND',
  'ZA': 'SOUTH AFRICA',
  'EG': 'EGYPT',
  'MA': 'MOROCCO',
  'DZ': 'ALGERIA',
  'TN': 'TUNISIA',
  'AE': 'UAE',
  'SA': 'SAUDI ARABIA',
  'IL': 'ISRAEL',
  'IR': 'IRAN',
  'IQ': 'IRAQ',
  'JO': 'JORDAN',
  'LB': 'LEBANON',
  'SY': 'SYRIA',
  'KW': 'KUWAIT',
  'QA': 'QATAR',
  'BH': 'BAHRAIN',
  'OM': 'OMAN',
  'YE': 'YEMEN',
}

export const getNationalityName = (code: string | null | undefined): string => {
  if (!code) return 'Not set'
  return nationalityMap[code.toUpperCase()] || code.toUpperCase()
}

export const getNationalityDisplay = (code: string | null | undefined): { code: string; name: string; flagUrl: string } | null => {
  if (!code) return null
  
  const upperCode = code.toUpperCase()
  return {
    code: upperCode,
    name: nationalityMap[upperCode] || upperCode,
    flagUrl: `https://flagcdn.com/${code.toLowerCase()}.svg`
  }
}
